### ISSUE TITLE
Mediapart changed its layout

### ISSUE THREAD

**Issue by dandelionmood** [AltGr/Calibre-french-news-rules#3]
Hi,

Mediapart recently changed its layout, and that actually broke the recipe.
I updated it here, if you want to update your version :) 

https://github.com/dandelionmood/Calibre-french-news-rules/blob/master/mediapart.recipe

Have a nice day !

**Comment by AltGr** [comment]
Ah great, noticed but didn't have time to fix yet. Thanks a bunch!
